# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: 'gcr.io/cloud-builders/docker:20.10.24'
    args: ['run', '--privileged', 'multiarch/qemu-user-static@sha256:fe60359c92e86a43cc87b3d906006245f77bfc0565676b80004cc666e4feb9f0']
    id: 'initialize-qemu'

  - name: 'gcr.io/cloud-builders/docker:20.10.24'
    args: ['buildx', 'create', '--name', 'multiarch', '--use']
    id: 'create-builder-and-use'

  - name: 'gcr.io/cloud-builders/docker:20.10.24'
    args: ['buildx', 'inspect', '--bootstrap']
    id: 'show-target-build-platforms'

  - name: 'gcr.io/cloud-builders/docker:20.10.24'
    id: 'build-legacy-dms'
    args: [
      'buildx', 'build',
      '--platform', 'linux/amd64',
      '-t', '$_CONTAINER_REGISTRY/legacy-dms:latest',
      '--push',
      'src/legacy-dms'
    ]

  - name: 'gcr.io/cloud-builders/docker:20.10.24'
    id: 'build-income-verification-api'
    args: [
      'buildx', 'build',
      '--platform', 'linux/amd64',
      '-t', '$_CONTAINER_REGISTRY/income-verification-api:latest',
      '--push',
      'src/income-verification-api'
    ]

  - name: 'gcr.io/cloud-builders/docker:20.10.24'
    id: 'build-corporate-email'
    args: [
      'buildx', 'build',
      '--platform', 'linux/amd64',
      '-t', '$_CONTAINER_REGISTRY/corporate-email:latest',
      '--push',
      'src/corporate-email'
    ]

substitutions:
  _CONTAINER_REGISTRY: ''
  _BUCKET_NAME: ''

logsBucket: 'gs://$_BUCKET_NAME/logs'

options:
  logging: GCS_ONLY
  env:
    - 'DOCKER_CLI_EXPERIMENTAL=enabled'
